# Generated by Django 4.2.25 on 2025-11-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='response_time',
            field=models.FloatField(blank=True, help_text='Seconds since question started', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
