# Generated by Django 4.2.25 on 2025-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_answer_response_time_session_current_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=300, help_text='Duration in minutes'),
        ),
    ]
